const Users = [
  {
    id: 1,
    profilePicture: require("./assets/images/users/1.jpg"),
    username: "Renata Maglio",
    mutualFriends: 14,
    town: "Oslo",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 2,
    profilePicture: require("./assets/images/users/2.jpg"),
    username: "Stefanie Carter",
    mutualFriends: 19,
    town: "Budapesta",
    comm: "Morbi mattis ut justo non semper. Ut cursus dignissim nisl.",
  },
  {
    id: 3,
    profilePicture: require("./assets/images/users/6.jpg"),
    username: "Antonio Jensen",
    mutualFriends: 10,
    town: "New York",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 4,
    profilePicture: require("./assets/images/users/3.jpg"),
    username: "Barbara Moore",
    mutualFriends: 54,
    town: "Brasov",
    comm: "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
  },
  {
    id: 5,
    profilePicture: require("./assets/images/users/4.jpg"),
    username: "Katherine Moss",
    mutualFriends: 64,
    town: "Iasi",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 6,
    profilePicture: require("./assets/images/users/5.jpg"),
    username: "Jeffrey Ward",
    mutualFriends: 44,
    town: "Cluj",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 7,
    profilePicture: require("./assets/images/users/7.jpg"),
    username: "Samantha Leon",
    mutualFriends: 74,
    town: "Berlin",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 8,
    profilePicture: require("./assets/images/users/8.jpg"),
    username: "Susan Ruiz",
    mutualFriends: 87,
    town: "Roma",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 9,
    profilePicture: require("./assets/images/users/11.jpg"),
    username: "Vincent Jacquot",
    mutualFriends: 7,
    town: "Verona",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 10,
    profilePicture: require("./assets/images/users/12.jpg"),
    username: "Justin Boyle",
    mutualFriends: 8,
    town: "Kiev",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 11,
    profilePicture: require("./assets/images/users/15.jpg"),
    username: "Chad Barrera",
    mutualFriends: 4,
    town: "Iasi",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 12,
    profilePicture: require("./assets/images/users/9.jpg"),
    username: "Debra Torres",
    mutualFriends: 19,
    town: "Oslo",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 13,
    profilePicture: require("./assets/images/users/18.jpg"),
    username: "Joe Stevens",
    mutualFriends: 13,
    town: "Milano",
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 14,
    profilePicture: require("./assets/images/users/14.jpg"),
    username: "Katie Hodges",
    mutualFriends: 23,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 15,
    profilePicture: require("./assets/images/users/10.jpg"),
    username: "James Chen",
    mutualFriends: 1,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 16,
    profilePicture: require("./assets/images/users/1.jpg"),
    username: "John Morgan",
    mutualFriends: 14,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 17,
    profilePicture: require("./assets/images/users/18.jpg"),
    username: "David Lane",
    mutualFriends: 17,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 18,
    profilePicture: require("./assets/images/users/17.jpg"),
    username: "Kelly Murray",
    mutualFriends: 52,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 19,
    profilePicture: require("./assets/images/users/15.jpg"),
    username: "Amanda Torres",
    mutualFriends: 7,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
  {
    id: 20,
    profilePicture: require("./assets/images/users/14.jpg"),
    username: "Ashley Gonzalez",
    mutualFriends: 4,
    comm: "Morbi non hendrerit eros, a blandit leo.",
  },
];

const Posts = [
  {
    id: 1,
    photo: require("./assets/images/posts/post1.jpg"),
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eaque consequuntur amet mollitia numquam, sed impedit.",
    date: "10 october 2022",
    userId: 1,
    like: 25,
    comment: 9,
  },
  {
    id: 2,
    photo: require("./assets/images/posts/post2.jpg"),
    desc: "Vivamus egestas orci ut lacinia dignissim. Ut in metus placerat, sollicitudin lorem eget, fringilla nibh. ",
    date: "9 october 2022",
    userId: 2,
    like: 59,
    comment: 5,
  },
  {
    id: 3,
    photo: require("./assets/images/posts/post3.jpg"),
    desc: "Donec ac elit sem. Etiam consectetur, urna a vulputate tristique, ipsum enim rutrum ante, facilisis bibendum velit sem nec odio. ",
    date: "12 october 2022",
    userId: 3,
    like: 102,
    comment: 20,
  },
];
export { Users, Posts };
